export const
    getTeacherDataByEmail = (email) => {
        return {
            query: `
                    query{
                       getTeacherByUserEmail(email:"${email}") {
                             resources{
                                code,
                                description,
                                createdAt,
                                location,
                                status,
                                type,
                                name
                            },
                            roomShiftClasses{
                                id,
                                day,
                                startTime,
                                endTime,
                                status,
                                subject{
                                    subjectName,
                                    subjectCode,
                                    subjectMajor
                                },
                            roomShift{
                                id,
                                grade,
                                section,
                                teacher{
                                    user{
                                        firstName,
                                        lastName
                                    }
                                },
                                room{
                                    id,
                                    roomName
                                }
                            },
                            students{
                            student_id,
                                user{
                                    email,
                                    firstName,
                                    lastName,
                                    suffix
                                }
                            }
                       },
                            activities{
                                roomShiftClass{
                                    id,
                                    day,
                                    startTime,
                                    endTime,
                                    subject{
                                    subjectName,
                                    subjectCode,
                                    subjectMajor
                                }
                            },
                            activity{
                                    activityTitle,
                                    description,
                                    date_end,
                                    date_created,
                                    type
                            }
                       }
                    }
            }
        `
        }
    }