export const
    CHANGE_RESOURCE_CODE= 'CHANGE_RESOURCE_CODE',
    CHANGE_CLASS_CODE='CHANGE_CLASS_CODE',
    CHANGE_DEADLINE= 'CHANGE_DEADLINE',
    CHANGE_SEMESTER= 'CHANGE_SEMESTER',
    CHANGE_QUARTER= 'CHANGE_QUARTER',
    CHANGE_LOW_GRADE= 'CHANGE_LOW_GRADE',
    CHANGE_HIGH_GRADE= 'CHANGE_HIGH_GRADE',
    CHANGE_DESCRIPTION = 'CHANGE_DESCRIPTION'