export const CHANGE_FILE = 'ADMIN_ACTIVITY_CHANGE_FILE',
    CHANGE_CLASS_ROOMSHIFT = 'ADMIN_ACTIVITY_CHANGE_ROOMSHIFT',
    CHANGE_SUBJECT = 'ADMIN_ACTIVITY_CHANGE_SUBJECT',
    CHANGE_ACTIVITY_NAME = 'CHANGE_ACTIVITY_NAME',
    CHANGE_ACTIVITY_TYPE = 'CHANGE_ACTIVITY_TYPE',
    CHANGE_ACTIVITY_DEADLINE_DATE = 'CHANGE_ACTIVITY_DEADLINE_DATE',
    CHANGE_ACTIVITY_DEADLINE_TIME = 'CHANGE_ACTIVITY_DEADLINE_TIME',
    CHANGE_ACTIVITY_DESCRIPTION = 'CHANGE_ACTIVITY_DESCRIPTION'
