/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 11/07/2021, Sunday
 **/
export const

    ROOM_DIALOG_ROOMNAME_CHANGE = "ROOM_DIALOG_ROOMNAME_CHANGE",
    ROOM_DIALOG_TIMESTART_CHANGE ="ROOM_DIALOG_TIMESTART_CHANGE",
    ROOM_DIALOG_TIMEEND_CHANGE = "ROOM_DIALOG_TIMEEND_CHANGE",

    SET_ERROR_ROOM_EMPTY = 'SET_ERROR_ROOM_EMPTY'