export const

    ROOM_DIALOG_ROOMNAME_CHANGE = "ROOM_DIALOG_ROOMNAME_CHANGE",
    ROOM_DIALOG_TIMESTART_CHANGE ="ROOM_DIALOG_TIMESTART_CHANGE",
    ROOM_DIALOG_TIMEEND_CHANGE = "ROOM_DIALOG_TIMEEND_CHANGE"