/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 11/07/2021, Sunday
 **/
export const
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    CHANGE_PASSWORD = 'CHANGE_PASSWORD',
    LOGIN = 'LOGIN',
    SUCCESS_LOGIN = 'SUCCESS_LOGIN',
    FAIL_LOGIN = 'FAIL_LOGIN',
    RE_LOGIN = 'RE_LOGIN',
    RESET_LOGIN_PAGE = 'RESET_LOGIN_PAGE',
    FAIL_PREREGISTER = 'FAIL_PREREGISTER',

    // for sign up action in auth
    CHANGE_ID = 'CHANGE_ID',
    CHANGE_FORM = 'CHANGE_FORM',
    REGISTER_OPEN = 'REGISTER_OPEN',
    REGISTER_CLOSE = 'REGISTER_CLOSE',
    REGISTER_INIT = 'REGISTER_INIT',
    REGISTER_FORM_CLOSE = 'REGISTER_FORM_CLOSE',
    REMEMBER_CLICK = 'REMEMBER_CLICK'
