export const
    AdminSubject = (state) => state.AdminSubject,
    AdminSubjectDialog = (state) => state.AdminSubjectDialog,
    AdminTeacher = (state) => state.AdminTeacher,
    AdminTeacherDialog = (state) => state.AdminDialogTeacher,
    AdminStudent = (state) => state.AdminStudent,
    AdminStudentDialog = (state) => state.AdminStudentDialog,
    AdminRoomDialog = (state) => state.AdminRoomDialog,
    AdminRoom = (state) => state.AdminRoom,
    AdminRoomShift = (state) => state.AdminRoomShift,
    AdminRoomShiftDialog = (state) => state.AdminRoomShiftDialog,
    AdminRoomClassDialog = (state) =>state.AdminClassDialog,
    AdminClass = (state) => state.AdminClass,
    AdminActivity = (state) => state.AdminActivity,
    AdminActivityDialog = (state) => state.AdminActivityDialog
