/**
 *
 *      This action type if for subjectID dialog in Admin
 *
 */

export const
    SUBJECT_ADD = "ADMIN_SUBJECT_ADD",
  SUBJECT_DELETE = "ADMIN_SUBJECT_DELETE",
  SUBJECT_UPDATE = "ADMIN_SUBJECT_UPDATE",

  CHANGE_SUBJECT_NAME = 'ADMIN_CHANGE_SUBJECT_NAME',
  CHANGE_SUBJECT_CODE = 'ADMIN_CHANGE_SUBJECT_CODE',
  CHANGE_SUBJECT_MAJOR = 'ADMIN_CHANGE_SUBJECT_MAJOR'