export const
    CHANGE_FIRSTNAME = 'CHANGE_FIRSTNAME',
    CHANGE_LASTNAME = 'CHANGE_LASTNAME',
    CHANGE_BIRTHDATE = 'CHANGE_BIRTHDATE',
    CHANGE_EMAIL = 'CHANGE_EMAIL',
    CHANGE_LANGUAGE = 'CHANGE_LANGUAGE'

