/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 27/07/2021, Tuesday
 **/

export const
    SET_ERROR_ID_EMPTY = (to) => to + '_SET_ERROR_ID_EMPTY',
    SET_ERROR_ROOM_EMPTY = (to) => to + '_SET_ERROR_ROOM_EMPTY',
    SET_ERROR_GRADE_EMPTY = (to) => to + '_SET_ERROR_GRADE_EMPTY',
    SET_ERROR_SECTION_EMPTY = (to) => to +'_SET_ERROR_SECTION_EMPTY',
    SET_ERROR_CURRICULUM_EMPTY = (to) => to +'_SET_ERROR_CURRICULUM_EMPTY',
    SET_ERROR_ROOM_SHIFT_EMPTY = (to) => to +'_SET_ERROR_ROOM_SHIFT_EMPTY',
    SET_ERROR_SUBJECT_EMPTY = (to) => to +'_SET_ERROR_SUBJECT_EMPTY',
    SET_ERROR_SUBJECT_NAME_EMPTY = (to) => to +'_SET_ERROR_SUBJECT_NAME_EMPTY',
    SET_ERROR_SUBJECT_CODE_EMPTY = (to) => to + '_SET_ERROR_SUBJECT_CODE_EMPTY',
    SET_ERROR_CURRICULUM_NAME_EMPTY = (to) => to + '_SET_ERROR_CURRICULUM_NAME_EMPTY',
    SET_ERROR_EMAIL_EMPTY = (to) => to + '_SET_ERROR_EMAIL',
    SET_ERROR_EMAIL_INVALID = (to) => to +'_SET_ERROR_EMAIL_INVALID',
    SET_ERROR_EMAIL_ALREADY_EXIST = (to) => to + '_SET_ERROR_EMAIL_ALREADY_EXIST',
    SET_ERROR_FIRST_NAME_EMPTY = (to) => to + '_SET_ERROR_FIRST_NAME_EMPTY',
    SET_ERROR_LAST_NAME_EMPTY = (to) => to + '_SET_ERROR_LAST_NAME_EMPTY',
    SET_ERROR_PASSWORD_EMPTY = (to) => to + '_SET_ERROR_PASSWORD_EMPTY',
    SET_ERROR_RETYPE_PASSWORD_EMPTY = (to) => to + '_SET_ERROR_RETYPE_PASSWORD_EMPTY',
    SET_ERROR_PASSWORD_NOT_MATCH = (to) => to+'_SET_ERROR_PASSWORD_NOT_MATCH',
    SET_ERROR_BIRTHDATE_EMPTY = (to) => to + '_SET_ERROR_BIRTHDATE_EMPTY',
    SET_ERROR_PASSWORD_STRENGTH = (to) => to + '_SET_ERROR_PASSWORD_STRENGTH'
