/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 11/07/2021, Sunday
 **/
export const
    ROOMSHIFT_DIALOG_ROOMGRADE_CHANGE = "ROOM_DIALOG_ROOMGRADE_CHANGE",
    ROOMSHIFT_DIALOG_ROOMSECTION_CHANGE ="ROOM_DIALOG_ROOMSECTION_CHANGE",
    ROOMSHIFT_DIALOG_TIMESTART_CHANGE ="ROOM_DIALOG_TIMESTART_CHANGE",
    ROOMSHIFT_DIALOG_TIMEEND_CHANGE = "ROOM_DIALOG_TIMEEND_CHANGE",
    ROOMSHIFT_DIALOG_ADVISER_CHANGE = 'ROOMSHIFT_DIALOG_ADVISER_CHANGE ',
    ROOMSHIFT_DIALOG_ROOM_SET = "ROOMSHIFT_DIALOG_ROOM_SET",
    ROOMSHIFT_DIALOG_ROOMSHIFT_SET= "ROOMSHIFT_DIALOG_ROOMSHIFT_SET",
    ROOMSHIFT_DIALOG_CURRICULUM_CHANGE = 'ROOMSHIFT_DIALOG_CURRICULUM_CHANGE'
