/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 11/07/2021, Sunday
 **/
export const
    CHANGE_ROOMCLASS_ROOMSHIFT_ID='CHANGE_ROOMCLASS_ROOMSHIFT_ID',
    CHANGE_ROOMCLASS_SUBJECT_ID='CHANGE_ROOMCLASS_SUBJECT_ID',
    CHANGE_ROOMCLASS_TIMESTART='CHANGE_ROOMCLASS_TIMESTART',
    CHANGE_ROOMCLASS_TIMEEND='CHANGE_ROOMCLASS_TIMEEND',
    CHANGE_ROOMCLASS_DAY='CHANGE_ROOMCLASS_DAY',
    CHANGE_ROOMCLASS_TEACHERID='CHANGE_ROOMCLASS_TEACHERID'
