/**
 * @author : Kurt Lupin Orioque
 * @mailto : kurtorioque112@gmail.com
 * @created : 11/07/2021, Sunday
 **/
export const
    getRoomShiftClass = (id) => {
        return {
            query: `
                    query{roomShiftClass(id:"${id}"){
                           day,
                           startTime,
                           endTime,  
                           roomShift{
                                grade,
                                section,
                                roomShiftName
                                room{
                                     roomName,
                                    }
                           },
                           teacher{
                                id
                                user{
                                    email,
                                    firstName,
                                    lastName,
                                    picture
                                }
                           },
                           students{
                                student_id,
                                user{
                                    email,
                                    firstName,
                                    lastName,
                                    picture
                                }
                           },
                           subject{
                                subjectName
                           },
                           teacherAssignments{
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                    location,
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                           },
                            teacherExams{ 
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                    location,
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                            },
                            teacherQuizzes{
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                   location,
                                   code,
                                   name,
                                   description,
                                   teacher{
                                        user{
                                          firstName,
                                          lastName
                                        }
                                   }
                                }
                            },
                            teacherLectures{
                                code,
                                createdAt,
                                resource{
                                    location,
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                            }
                           
                    }
            }
        `
        }
    },
    getRoomShiftClassBasic = (id) => {
        return {
            query: `
                    query{roomShiftClass(id:"${id}"){
                           id,
                           day,
                           startTime,
                           endTime,  
                           roomShift{
                                id,
                                grade,
                                section,
                           },
                           teacher{
                                id
                                user{
                                    email,
                                    firstName,
                                    lastName,
                                }
                           },
                           subject{
                                id,
                                subjectCode,
                                subjectName
                           },
                           students{
                                student_id,
                                user{
                                    email,
                                    firstName,
                                    lastName,
                                    picture
                                }
                           }                   
                    }
            }
        `
        }
    }