export const
    getRoomShiftClass = (id) => {
        return {
            query: `
                    query{roomShiftClass(id:"${id}"){
                           day,
                           startTime,
                           endTime,  
                           roomShift{
                                grade,
                                section,
                                roomShiftName
                                room{
                                     roomName,
                                    }
                           },
                           teacher{
                                id
                                user{
                                    firstName,
                                    lastName
                                }
                           },
                           students{
                                student_id,
                                user{
                                    firstName,
                                    lastName
                                }
                           },
                           subject{
                                subjectName
                           },
                           teacherAssignments{
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                           },
                            teacherExams{ 
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                            },
                            teacherQuizzes{
                                code,
                                highGrade,
                                lowGrade,
                                deadLine,
                                createdAt
                                resource{
                                   code,
                                   name,
                                   description,
                                   teacher{
                                        user{
                                          firstName,
                                          lastName
                                        }
                                   }
                                }
                            },
                            teacherLectures{
                                code,
                                createdAt,
                                resource{
                                    code,
                                    name,
                                    description,
                                    teacher{
                                        user{
                                            firstName,
                                            lastName
                                        }
                                    }
                                }
                            }
                           
                    }
            }
        `}
    }